# Generated by Django 5.2.12 on 2026-04-04 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('is_pre_trade', models.BooleanField(default=True)),
                ('is_post_trade', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_checklisttemplate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('TRADE_REVIEW', 'Trade Review'), ('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_REVIEW', 'Weekly Review'), ('MONTHLY_REVIEW', 'Monthly Review'), ('LESSON_LEARNED', 'Lesson Learned'), ('STRATEGY_NOTES', 'Strategy Notes'), ('MARKET_OBSERVATION', 'Market Observation'), ('PSYCHOLOGY', 'Psychology'), ('GOALS', 'Goals'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pre_trading_mood', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('BAD', 'Bad'), ('TERRIBLE', 'Terrible')], max_length=10, null=True)),
                ('post_trading_mood', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('BAD', 'Bad'), ('TERRIBLE', 'Terrible')], max_length=10, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('entry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_trades', models.ManyToManyField(blank=True, related_name='journal_entries', to='trades.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_journalentry',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='TradeChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_items', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.checklisttemplate')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trades.trade')),
            ],
            options={
                'db_table': 'journal_tradechecklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('PROFIT', 'Profit Target'), ('RISK', 'Risk Management'), ('DISCIPLINE', 'Discipline'), ('PSYCHOLOGY', 'Psychology'), ('STRATEGY', 'Strategy'), ('EDUCATION', 'Education')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=10)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_tradinggoal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_criteria', models.TextField(blank=True, null=True)),
                ('exit_criteria', models.TextField(blank=True, null=True)),
                ('risk_management_rules', models.TextField(blank=True, null=True)),
                ('position_sizing', models.TextField(blank=True, null=True)),
                ('markets_traded', models.JSONField(blank=True, default=list)),
                ('timeframes', models.JSONField(blank=True, default=list)),
                ('pre_trading_routine', models.TextField(blank=True, null=True)),
                ('post_trading_routine', models.TextField(blank=True, null=True)),
                ('max_risk_per_trade', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('max_weekly_loss', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_tradingplan',
                'ordering': ['-created_at'],
            },
        ),
    ]
