# Generated by Django 5.2.12 on 2026-04-04 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5SetupGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mt5_integration_mt5setupguide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MT5Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('investor_password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='DISCONNECTED', max_length=15)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('free_margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_interval', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mt5_integration_mt5account',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'account_number', 'server')},
            },
        ),
        migrations.CreateModel(
            name='MT5ConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('CONNECT', 'Connect'), ('DISCONNECT', 'Disconnect'), ('SYNC', 'Sync'), ('ERROR', 'Error'), ('INFO', 'Info')], max_length=15)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='mt5_integration.mt5account')),
            ],
            options={
                'db_table': 'mt5_integration_mt5connectionlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MT5TradeImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('imported_trades', models.IntegerField(default=0)),
                ('skipped_trades', models.IntegerField(default=0)),
                ('failed_trades', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='mt5_integration.mt5account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mt5_integration_mt5tradeimport',
                'ordering': ['-created_at'],
            },
        ),
    ]
