# Generated by Django 5.2.12 on 2026-04-04 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('MT5', 'MetaTrader 5'), ('MT4', 'MetaTrader 4'), ('CSV', 'CSV File'), ('MANUAL', 'Manual Entry')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='trade_imports/')),
                ('mt5_server', models.CharField(blank=True, max_length=255, null=True)),
                ('mt5_login', models.CharField(blank=True, max_length=50, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('imported_trades', models.IntegerField(default=0)),
                ('failed_trades', models.IntegerField(default=0)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades_tradeimport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_rules', models.TextField(blank=True, null=True)),
                ('exit_rules', models.TextField(blank=True, null=True)),
                ('risk_management', models.TextField(blank=True, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades_strategy',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('market_type', models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Cryptocurrency'), ('STOCKS', 'Stocks'), ('INDICES', 'Indices'), ('COMMODITIES', 'Commodities'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options')], default='FOREX', max_length=15)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateTimeField()),
                ('position_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_loss_pips', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_loss_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', 'Daily'), ('W1', 'Weekly'), ('MN', 'Monthly')], default='H1', max_length=3)),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('setup_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_trade_emotion', models.CharField(choices=[('CONFIDENT', 'Confident'), ('FEARFUL', 'Fearful'), ('GREEDY', 'Greedy'), ('NEUTRAL', 'Neutral'), ('IMPATIENT', 'Impatient'), ('REVENGE', 'Revenge Trading'), ('FOMO', 'FOMO')], default='NEUTRAL', max_length=20)),
                ('post_trade_emotion', models.CharField(blank=True, choices=[('CONFIDENT', 'Confident'), ('FEARFUL', 'Fearful'), ('GREEDY', 'Greedy'), ('NEUTRAL', 'Neutral'), ('IMPATIENT', 'Impatient'), ('REVENGE', 'Revenge Trading'), ('FOMO', 'FOMO')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('entry_screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/entries/')),
                ('exit_screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/exits/')),
                ('mt5_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('mt5_magic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mt5_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades_trade',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='trades_trad_user_id_aee238_idx'), models.Index(fields=['user', 'symbol'], name='trades_trad_user_id_089547_idx'), models.Index(fields=['user', 'entry_date'], name='trades_trad_user_id_82a273_idx'), models.Index(fields=['user', 'strategy'], name='trades_trad_user_id_93270f_idx')],
            },
        ),
    ]
