# Generated by Django 5.2.12 on 2026-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net monetary P&L in account currency (USD). For MT5 trades this is sourced directly from MT5 (profit + swap + commission). For manual trades it is calculated by calculate_profit_loss().', max_digits=20, null=True),
        ),
    ]
