# Generated by Django 5.2.12 on 2026-04-04 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=10)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_drawdown_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_trade', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_win', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('largest_win', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('largest_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_consecutive_wins', models.IntegerField(default=0)),
                ('max_consecutive_losses', models.IntegerField(default=0)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_performance_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('PATTERN', 'Pattern'), ('MISTAKE', 'Mistake'), ('IMPROVEMENT', 'Improvement'), ('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('impact_score', models.IntegerField(default=0)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_trading_insight',
                'ordering': ['-created_at'],
            },
        ),
    ]
