# Generated by Django 5.2.12 on 2026-04-04 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('event_type', models.CharField(choices=[('GDP', 'GDP'), ('EMPLOYMENT', 'Employment'), ('INFLATION', 'Inflation'), ('INTEREST_RATE', 'Interest Rate'), ('RETAIL_SALES', 'Retail Sales'), ('MANUFACTURING', 'Manufacturing'), ('TRADE_BALANCE', 'Trade Balance'), ('CONSUMER_CONFIDENCE', 'Consumer Confidence'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('forecast', models.CharField(blank=True, max_length=50, null=True)),
                ('previous', models.CharField(blank=True, max_length=50, null=True)),
                ('actual', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(default='ForexFactory', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_data_economicevent',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_type', models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Cryptocurrency'), ('STOCKS', 'Stocks'), ('INDICES', 'Indices'), ('COMMODITIES', 'Commodities'), ('FUTURES', 'Futures')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('quote_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('pip_value', models.DecimalField(decimal_places=8, default=0.0001, max_digits=20)),
                ('contract_size', models.DecimalField(decimal_places=8, default=100000, max_digits=20)),
                ('min_lot_size', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('max_lot_size', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('session_open', models.TimeField(blank=True, null=True)),
                ('session_close', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_data_instrument',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_pairs', models.JSONField(blank=True, default=list)),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market News',
                'db_table': 'market_data_marketnews',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('market_type', models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Cryptocurrency'), ('STOCKS', 'Stocks'), ('INDICES', 'Indices'), ('COMMODITIES', 'Commodities')], max_length=15)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('change_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_data_marketprice',
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'market_type')},
            },
        ),
    ]
