# Generated by Django 5.2.12 on 2026-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002 fix field lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketnews',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
